- name: start iri
  systemd:
    daemon_reload: true
    name: iri.service
    state: started
    enabled: true
  register: iri_started

- name: restart iri
  systemd:
    name: iri.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: not iri_started.changed

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted
