- name: restart iotacaddy
  systemd:
    name: iotacaddy.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: iotacaddy_started is not defined or not iotacaddy_started.changed
